// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flow_checkpoints.sql

package database

import (
	"context"
	"encoding/json"
)

const createFlowCheckpoint = `-- name: CreateFlowCheckpoint :one
INSERT INTO flow_checkpoints (
  flow_id,
  kind,
  payload,
  active
)
VALUES (
  $1, $2, $3, $4
)
RETURNING id, flow_id, kind, payload, active, created_at, consumed_at
`

type CreateFlowCheckpointParams struct {
	FlowID  int64           `json:"flow_id"`
	Kind    string          `json:"kind"`
	Payload json.RawMessage `json:"payload"`
	Active  bool            `json:"active"`
}

func (q *Queries) CreateFlowCheckpoint(ctx context.Context, arg CreateFlowCheckpointParams) (FlowCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, createFlowCheckpoint,
		arg.FlowID,
		arg.Kind,
		arg.Payload,
		arg.Active,
	)
	var i FlowCheckpoint
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Kind,
		&i.Payload,
		&i.Active,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const deactivateFlowCheckpoints = `-- name: DeactivateFlowCheckpoints :exec
UPDATE flow_checkpoints
SET active = FALSE,
    consumed_at = CURRENT_TIMESTAMP
WHERE flow_id = $1 AND active = TRUE
`

func (q *Queries) DeactivateFlowCheckpoints(ctx context.Context, flowID int64) error {
	_, err := q.db.ExecContext(ctx, deactivateFlowCheckpoints, flowID)
	return err
}

const getLatestActiveFlowCheckpoint = `-- name: GetLatestActiveFlowCheckpoint :one
SELECT
  fc.id, fc.flow_id, fc.kind, fc.payload, fc.active, fc.created_at, fc.consumed_at
FROM flow_checkpoints fc
INNER JOIN flows f ON fc.flow_id = f.id
WHERE fc.flow_id = $1 AND fc.active = TRUE AND f.deleted_at IS NULL
ORDER BY fc.created_at DESC, fc.id DESC
LIMIT 1
`

func (q *Queries) GetLatestActiveFlowCheckpoint(ctx context.Context, flowID int64) (FlowCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getLatestActiveFlowCheckpoint, flowID)
	var i FlowCheckpoint
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Kind,
		&i.Payload,
		&i.Active,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const markFlowCheckpointConsumed = `-- name: MarkFlowCheckpointConsumed :one
UPDATE flow_checkpoints
SET active = FALSE,
    consumed_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, flow_id, kind, payload, active, created_at, consumed_at
`

func (q *Queries) MarkFlowCheckpointConsumed(ctx context.Context, id int64) (FlowCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, markFlowCheckpointConsumed, id)
	var i FlowCheckpoint
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Kind,
		&i.Payload,
		&i.Active,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}
