// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mcp_servers.sql

package database

import (
    "context"
    "database/sql"
    "encoding/json"
)

const createMcpServer = `-- name: CreateMcpServer :one
INSERT INTO mcp_servers (
  name, transport, stdio_command, stdio_args, stdio_env, sse_url, sse_headers, tools
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, transport, stdio_command, stdio_args, stdio_env, sse_url, sse_headers, tools, created_at, updated_at
`

type CreateMcpServerParams struct {
    Name         string          `json:"name"`
    Transport    McpTransport    `json:"transport"`
    StdioCommand sql.NullString  `json:"stdio_command"`
    StdioArgs    sql.NullString  `json:"stdio_args"`
    StdioEnv     json.RawMessage `json:"stdio_env"`
    SseUrl       sql.NullString  `json:"sse_url"`
    SseHeaders   json.RawMessage `json:"sse_headers"`
    Tools        json.RawMessage `json:"tools"`
}

func (q *Queries) CreateMcpServer(ctx context.Context, arg CreateMcpServerParams) (McpServer, error) {
    row := q.db.QueryRowContext(ctx, createMcpServer,
        arg.Name,
        arg.Transport,
        arg.StdioCommand,
        arg.StdioArgs,
        arg.StdioEnv,
        arg.SseUrl,
        arg.SseHeaders,
        arg.Tools,
    )
    var i McpServer
    err := row.Scan(
        &i.ID,
        &i.Name,
        &i.Transport,
        &i.StdioCommand,
        &i.StdioArgs,
        &i.StdioEnv,
        &i.SseUrl,
        &i.SseHeaders,
        &i.Tools,
        &i.CreatedAt,
        &i.UpdatedAt,
    )
    return i, err
}

const getMcpServer = `-- name: GetMcpServer :one
SELECT id, name, transport, stdio_command, stdio_args, stdio_env, sse_url, sse_headers, tools, created_at, updated_at
FROM mcp_servers
WHERE id = $1
`

func (q *Queries) GetMcpServer(ctx context.Context, id int64) (McpServer, error) {
    row := q.db.QueryRowContext(ctx, getMcpServer, id)
    var i McpServer
    err := row.Scan(
        &i.ID,
        &i.Name,
        &i.Transport,
        &i.StdioCommand,
        &i.StdioArgs,
        &i.StdioEnv,
        &i.SseUrl,
        &i.SseHeaders,
        &i.Tools,
        &i.CreatedAt,
        &i.UpdatedAt,
    )
    return i, err
}

const getMcpServers = `-- name: GetMcpServers :many
SELECT id, name, transport, stdio_command, stdio_args, stdio_env, sse_url, sse_headers, tools, created_at, updated_at
FROM mcp_servers
ORDER BY created_at DESC
`

func (q *Queries) GetMcpServers(ctx context.Context) ([]McpServer, error) {
    rows, err := q.db.QueryContext(ctx, getMcpServers)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    var items []McpServer
    for rows.Next() {
        var i McpServer
        if err := rows.Scan(
            &i.ID,
            &i.Name,
            &i.Transport,
            &i.StdioCommand,
            &i.StdioArgs,
            &i.StdioEnv,
            &i.SseUrl,
            &i.SseHeaders,
            &i.Tools,
            &i.CreatedAt,
            &i.UpdatedAt,
        ); err != nil {
            return nil, err
        }
        items = append(items, i)
    }
    if err := rows.Close(); err != nil {
        return nil, err
    }
    if err := rows.Err(); err != nil {
        return nil, err
    }
    return items, nil
}

const getMcpServerByName = `-- name: GetMcpServerByName :one
SELECT id, name, transport, stdio_command, stdio_args, stdio_env, sse_url, sse_headers, tools, created_at, updated_at
FROM mcp_servers
WHERE name = $1
`

func (q *Queries) GetMcpServerByName(ctx context.Context, name string) (McpServer, error) {
    row := q.db.QueryRowContext(ctx, getMcpServerByName, name)
    var i McpServer
    err := row.Scan(
        &i.ID,
        &i.Name,
        &i.Transport,
        &i.StdioCommand,
        &i.StdioArgs,
        &i.StdioEnv,
        &i.SseUrl,
        &i.SseHeaders,
        &i.Tools,
        &i.CreatedAt,
        &i.UpdatedAt,
    )
    return i, err
}

const updateMcpServer = `-- name: UpdateMcpServer :one
UPDATE mcp_servers
SET name = $1,
    transport = $2,
    stdio_command = $3,
    stdio_args = $4,
    stdio_env = $5,
    sse_url = $6,
    sse_headers = $7,
    tools = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $9
RETURNING id, name, transport, stdio_command, stdio_args, stdio_env, sse_url, sse_headers, tools, created_at, updated_at
`

type UpdateMcpServerParams struct {
    Name         string          `json:"name"`
    Transport    McpTransport    `json:"transport"`
    StdioCommand sql.NullString  `json:"stdio_command"`
    StdioArgs    sql.NullString  `json:"stdio_args"`
    StdioEnv     json.RawMessage `json:"stdio_env"`
    SseUrl       sql.NullString  `json:"sse_url"`
    SseHeaders   json.RawMessage `json:"sse_headers"`
    Tools        json.RawMessage `json:"tools"`
    ID           int64           `json:"id"`
}

func (q *Queries) UpdateMcpServer(ctx context.Context, arg UpdateMcpServerParams) (McpServer, error) {
    row := q.db.QueryRowContext(ctx, updateMcpServer,
        arg.Name,
        arg.Transport,
        arg.StdioCommand,
        arg.StdioArgs,
        arg.StdioEnv,
        arg.SseUrl,
        arg.SseHeaders,
        arg.Tools,
        arg.ID,
    )
    var i McpServer
    err := row.Scan(
        &i.ID,
        &i.Name,
        &i.Transport,
        &i.StdioCommand,
        &i.StdioArgs,
        &i.StdioEnv,
        &i.SseUrl,
        &i.SseHeaders,
        &i.Tools,
        &i.CreatedAt,
        &i.UpdatedAt,
    )
    return i, err
}

const deleteMcpServer = `-- name: DeleteMcpServer :exec
DELETE FROM mcp_servers
WHERE id = $1
`

func (q *Queries) DeleteMcpServer(ctx context.Context, id int64) error {
    _, err := q.db.ExecContext(ctx, deleteMcpServer, id)
    return err
}
